### ISSUE TITLE
How to get poe credentails?

### ISSUE THREAD

**Issue by lexer21** [maximumstock/poe-stash-indexer#371]
Hello Maximilian,

I was trying to start up the project on local dev enviroment but it seems im missing `.env.development` file I noticed you provide a template but I don't have the client id and secret for poe api. I see that i have to write an email to GGG to get the oauth access, can you provide any tips or email template (type of client, grant type, scopes...)  on what to write in the email request so it gets acctually accepted?

Also thank you for sharing this repository, im currently learning Rust and this seems like a great repostiory to learn from 👍

**Comment by maximumstock** [comment]
Hey there, here is what I wrote them:

> I'd like to register a personal project to access the public stash tab API:
> 
> Your PoE account name: $accountName
> Your application's name: $whateverYouLike
> The scopes you are interested in: service:psapi

It took a few day then everything was set-up.

**Comment by lexer21** [comment]
I got the oauth credentials, thank you for your help.
